mc-mysql:
  image: "mysql:5.7"
  log_driver: "none"
  environment:
    MYSQL_ROOT_PASSWORD: metadata
    MYSQL_DATABASE: metadata
    MYSQL_PASSWORD: metadata
    MYSQL_USER: metadata
  volumes:
    - ./data:/docker-entrypoint-initdb.d
mc-es:
  image: "metadata/registry-elasticsearch:2"
  log_driver: "none"
mc-storage:
  image: "busybox"
  volumes:
    - /usr/local/tomcat/storage
mc:
  image: "metadata/registry:2"
  links:
    - "mc-mysql"
    - "mc-es"
  environment:
    CATALINA_OPTS: "-Djava.awt.headless=true -Dfile.encoding=UTF-8 -server -Xms1g -Xmx2g -XX:NewSize=512m -XX:MaxNewSize=512m -XX:PermSize=512m -XX:MaxPermSize=512m -XX:+DisableExplicitGC"
    MC_USE_LOCAL_STORAGE: "true"
  volumes_from:
    - mc-storage
